package net.mcreator.lsfurniture.block.listener;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.mcreator.lsfurniture.init.LsFurnitureModBlockEntities;
import net.mcreator.lsfurniture.block.renderer.WarpedWartOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.WarpedWarpedWartSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.WarpedWarpedWartCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.WarpedWardrobeTileRenderer;
import net.mcreator.lsfurniture.block.renderer.WarpedWardrobe2TileRenderer;
import net.mcreator.lsfurniture.block.renderer.WarpedWardrobe1TileRenderer;
import net.mcreator.lsfurniture.block.renderer.WarpedSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.WarpedOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.WarpedDrawerTileRenderer;
import net.mcreator.lsfurniture.block.renderer.WarpedDeskTileRenderer;
import net.mcreator.lsfurniture.block.renderer.WarpedCupboardTileRenderer;
import net.mcreator.lsfurniture.block.renderer.WarpedCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.ToasterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.SprucewardrobeTileRenderer;
import net.mcreator.lsfurniture.block.renderer.SpruceWardrobe2TileRenderer;
import net.mcreator.lsfurniture.block.renderer.SpruceWardrobe1TileRenderer;
import net.mcreator.lsfurniture.block.renderer.SpruceSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.SpruceOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.SpruceDrawerTileRenderer;
import net.mcreator.lsfurniture.block.renderer.SpruceDeskTileRenderer;
import net.mcreator.lsfurniture.block.renderer.SpruceCupboardTileRenderer;
import net.mcreator.lsfurniture.block.renderer.SpruceCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.SpruceAndesiteSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.SpruceAndesiteCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.QuartzOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.OakWardrobe2TileRenderer;
import net.mcreator.lsfurniture.block.renderer.OakWardrobe1TileRenderer;
import net.mcreator.lsfurniture.block.renderer.OakWardrobe0TileRenderer;
import net.mcreator.lsfurniture.block.renderer.OakSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.OakOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.OakDrawerTileRenderer;
import net.mcreator.lsfurniture.block.renderer.OakDeskTileRenderer;
import net.mcreator.lsfurniture.block.renderer.OakCupboardTileRenderer;
import net.mcreator.lsfurniture.block.renderer.OakCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.OakBricksSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.OakBricksCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.NetherWartOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.NetherBricksOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.MicrowaveTileRenderer;
import net.mcreator.lsfurniture.block.renderer.MangroveWardrobeTileRenderer;
import net.mcreator.lsfurniture.block.renderer.MangroveWardrobe2TileRenderer;
import net.mcreator.lsfurniture.block.renderer.MangroveWardrobe1TileRenderer;
import net.mcreator.lsfurniture.block.renderer.MangroveSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.MangroveQuartzSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.MangroveQuartzCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.MangroveOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.MangroveDrawerTileRenderer;
import net.mcreator.lsfurniture.block.renderer.MangroveDeskTileRenderer;
import net.mcreator.lsfurniture.block.renderer.MangroveCupboardTileRenderer;
import net.mcreator.lsfurniture.block.renderer.MangroveCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.KettleTileRenderer;
import net.mcreator.lsfurniture.block.renderer.JungleWardrobeTileRenderer;
import net.mcreator.lsfurniture.block.renderer.JungleWardrobe2TileRenderer;
import net.mcreator.lsfurniture.block.renderer.JungleWardrobe1TileRenderer;
import net.mcreator.lsfurniture.block.renderer.JungleSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.JungleOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.JungleNetherBricksSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.JungleNetherBricksCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.JungleDrawerTileRenderer;
import net.mcreator.lsfurniture.block.renderer.JungleDeskTileRenderer;
import net.mcreator.lsfurniture.block.renderer.JungleCupboardTileRenderer;
import net.mcreator.lsfurniture.block.renderer.JungleCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.GraniteOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.FridgeFreezerBlockTileRenderer;
import net.mcreator.lsfurniture.block.renderer.FridgeFreezerBlock2TileRenderer;
import net.mcreator.lsfurniture.block.renderer.FridgeFreezerBlock1TileRenderer;
import net.mcreator.lsfurniture.block.renderer.DioriteOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.DeepslateOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.Darkoakwardrobe2TileRenderer;
import net.mcreator.lsfurniture.block.renderer.Darkoakwardrobe1TileRenderer;
import net.mcreator.lsfurniture.block.renderer.Darkoakwardrobe0TileRenderer;
import net.mcreator.lsfurniture.block.renderer.DarkOakSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.DarkOakOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.DarkOakDrawerTileRenderer;
import net.mcreator.lsfurniture.block.renderer.DarkOakDeskTileRenderer;
import net.mcreator.lsfurniture.block.renderer.DarkOakDeepslateSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.DarkOakDeepslateCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.DarkOakCupboardTileRenderer;
import net.mcreator.lsfurniture.block.renderer.DarkOakCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.CrimsonWardrobeTileRenderer;
import net.mcreator.lsfurniture.block.renderer.CrimsonWardrobe2TileRenderer;
import net.mcreator.lsfurniture.block.renderer.CrimsonWardrobe1TileRenderer;
import net.mcreator.lsfurniture.block.renderer.CrimsonSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.CrimsonOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.CrimsonNetherWartSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.CrimsonNetherWartCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.CrimsonDrawerTileRenderer;
import net.mcreator.lsfurniture.block.renderer.CrimsonDeskTileRenderer;
import net.mcreator.lsfurniture.block.renderer.CrimsonCupboardTileRenderer;
import net.mcreator.lsfurniture.block.renderer.CrimsonCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.BricksOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.BirchWardrobeTileRenderer;
import net.mcreator.lsfurniture.block.renderer.BirchWardrobe2TileRenderer;
import net.mcreator.lsfurniture.block.renderer.BirchWardrobe1TileRenderer;
import net.mcreator.lsfurniture.block.renderer.BirchSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.BirchOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.BirchGraniteSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.BirchGraniteCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.BirchDrawerTileRenderer;
import net.mcreator.lsfurniture.block.renderer.BirchDeskTileRenderer;
import net.mcreator.lsfurniture.block.renderer.BirchCupboardTileRenderer;
import net.mcreator.lsfurniture.block.renderer.BirchCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.AndesiteOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.AcaciaWardrobeTileRenderer;
import net.mcreator.lsfurniture.block.renderer.AcaciaWardrobe2TileRenderer;
import net.mcreator.lsfurniture.block.renderer.AcaciaWardrobe1TileRenderer;
import net.mcreator.lsfurniture.block.renderer.AcaciaSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.AcaciaOvenTileRenderer;
import net.mcreator.lsfurniture.block.renderer.AcaciaDrawerTileRenderer;
import net.mcreator.lsfurniture.block.renderer.AcaciaDioriteSinkTileRenderer;
import net.mcreator.lsfurniture.block.renderer.AcaciaDioriteCounterTileRenderer;
import net.mcreator.lsfurniture.block.renderer.AcaciaDeskTileRenderer;
import net.mcreator.lsfurniture.block.renderer.AcaciaCupboardTileRenderer;
import net.mcreator.lsfurniture.block.renderer.AcaciaCounterTileRenderer;
import net.mcreator.lsfurniture.LsFurnitureMod;

@Mod.EventBusSubscriber(modid = LsFurnitureMod.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ClientListener {
	@OnlyIn(Dist.CLIENT)
	@SubscribeEvent
	public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event) {
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.MICROWAVE.get(), context -> new MicrowaveTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.KETTLE.get(), context -> new KettleTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.TOASTER.get(), context -> new ToasterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.OAK_WARDROBE_0.get(), context -> new OakWardrobe0TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.SPRUCEWARDROBE.get(), context -> new SprucewardrobeTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.BIRCH_WARDROBE.get(), context -> new BirchWardrobeTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.JUNGLE_WARDROBE.get(), context -> new JungleWardrobeTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.ACACIA_WARDROBE.get(), context -> new AcaciaWardrobeTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DARKOAKWARDROBE_0.get(), context -> new Darkoakwardrobe0TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.MANGROVE_WARDROBE.get(), context -> new MangroveWardrobeTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.CRIMSON_WARDROBE.get(), context -> new CrimsonWardrobeTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.WARPED_WARDROBE.get(), context -> new WarpedWardrobeTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.OAK_DESK.get(), context -> new OakDeskTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.SPRUCE_DESK.get(), context -> new SpruceDeskTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.BIRCH_DESK.get(), context -> new BirchDeskTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.JUNGLE_DESK.get(), context -> new JungleDeskTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.ACACIA_DESK.get(), context -> new AcaciaDeskTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DARK_OAK_DESK.get(), context -> new DarkOakDeskTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.MANGROVE_DESK.get(), context -> new MangroveDeskTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.CRIMSON_DESK.get(), context -> new CrimsonDeskTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.WARPED_DESK.get(), context -> new WarpedDeskTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.OAK_DRAWER.get(), context -> new OakDrawerTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.SPRUCE_DRAWER.get(), context -> new SpruceDrawerTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.BIRCH_DRAWER.get(), context -> new BirchDrawerTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.JUNGLE_DRAWER.get(), context -> new JungleDrawerTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.ACACIA_DRAWER.get(), context -> new AcaciaDrawerTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DARK_OAK_DRAWER.get(), context -> new DarkOakDrawerTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.MANGROVE_DRAWER.get(), context -> new MangroveDrawerTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.CRIMSON_DRAWER.get(), context -> new CrimsonDrawerTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.WARPED_DRAWER.get(), context -> new WarpedDrawerTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.OAK_COUNTER.get(), context -> new OakCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.OAK_BRICKS_COUNTER.get(), context -> new OakBricksCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.SPRUCE_COUNTER.get(), context -> new SpruceCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.SPRUCE_ANDESITE_COUNTER.get(), context -> new SpruceAndesiteCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.BIRCH_COUNTER.get(), context -> new BirchCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.BIRCH_GRANITE_COUNTER.get(), context -> new BirchGraniteCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.JUNGLE_COUNTER.get(), context -> new JungleCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.JUNGLE_NETHER_BRICKS_COUNTER.get(), context -> new JungleNetherBricksCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.ACACIA_COUNTER.get(), context -> new AcaciaCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.ACACIA_DIORITE_COUNTER.get(), context -> new AcaciaDioriteCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DARK_OAK_COUNTER.get(), context -> new DarkOakCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DARK_OAK_DEEPSLATE_COUNTER.get(), context -> new DarkOakDeepslateCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.MANGROVE_COUNTER.get(), context -> new MangroveCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.MANGROVE_QUARTZ_COUNTER.get(), context -> new MangroveQuartzCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.CRIMSON_COUNTER.get(), context -> new CrimsonCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.CRIMSON_NETHER_WART_COUNTER.get(), context -> new CrimsonNetherWartCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.WARPED_COUNTER.get(), context -> new WarpedCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.WARPED_WARPED_WART_COUNTER.get(), context -> new WarpedWarpedWartCounterTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.OAK_OVEN.get(), context -> new OakOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.BRICKS_OVEN.get(), context -> new BricksOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.SPRUCE_OVEN.get(), context -> new SpruceOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.ANDESITE_OVEN.get(), context -> new AndesiteOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.BIRCH_OVEN.get(), context -> new BirchOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.GRANITE_OVEN.get(), context -> new GraniteOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.JUNGLE_OVEN.get(), context -> new JungleOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.NETHER_BRICKS_OVEN.get(), context -> new NetherBricksOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.ACACIA_OVEN.get(), context -> new AcaciaOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DIORITE_OVEN.get(), context -> new DioriteOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DARK_OAK_OVEN.get(), context -> new DarkOakOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DEEPSLATE_OVEN.get(), context -> new DeepslateOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.MANGROVE_OVEN.get(), context -> new MangroveOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.QUARTZ_OVEN.get(), context -> new QuartzOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.WARPED_OVEN.get(), context -> new WarpedOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.WARPED_WART_OVEN.get(), context -> new WarpedWartOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.CRIMSON_OVEN.get(), context -> new CrimsonOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.NETHER_WART_OVEN.get(), context -> new NetherWartOvenTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.FRIDGE_FREEZER_BLOCK.get(), context -> new FridgeFreezerBlockTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.OAK_SINK.get(), context -> new OakSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.OAK_BRICKS_SINK.get(), context -> new OakBricksSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.SPRUCE_SINK.get(), context -> new SpruceSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.SPRUCE_ANDESITE_SINK.get(), context -> new SpruceAndesiteSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.BIRCH_SINK.get(), context -> new BirchSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.BIRCH_GRANITE_SINK.get(), context -> new BirchGraniteSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.JUNGLE_SINK.get(), context -> new JungleSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.JUNGLE_NETHER_BRICKS_SINK.get(), context -> new JungleNetherBricksSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.ACACIA_SINK.get(), context -> new AcaciaSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.ACACIA_DIORITE_SINK.get(), context -> new AcaciaDioriteSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DARK_OAK_SINK.get(), context -> new DarkOakSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DARK_OAK_DEEPSLATE_SINK.get(), context -> new DarkOakDeepslateSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.MANGROVE_SINK.get(), context -> new MangroveSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.MANGROVE_QUARTZ_SINK.get(), context -> new MangroveQuartzSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.CRIMSON_SINK.get(), context -> new CrimsonSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.CRIMSON_NETHER_WART_SINK.get(), context -> new CrimsonNetherWartSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.WARPED_SINK.get(), context -> new WarpedSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.WARPED_WARPED_WART_SINK.get(), context -> new WarpedWarpedWartSinkTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.OAK_CUPBOARD.get(), context -> new OakCupboardTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.SPRUCE_CUPBOARD.get(), context -> new SpruceCupboardTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.BIRCH_CUPBOARD.get(), context -> new BirchCupboardTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.JUNGLE_CUPBOARD.get(), context -> new JungleCupboardTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.ACACIA_CUPBOARD.get(), context -> new AcaciaCupboardTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DARK_OAK_CUPBOARD.get(), context -> new DarkOakCupboardTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.MANGROVE_CUPBOARD.get(), context -> new MangroveCupboardTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.CRIMSON_CUPBOARD.get(), context -> new CrimsonCupboardTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.WARPED_CUPBOARD.get(), context -> new WarpedCupboardTileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.FRIDGE_FREEZER_BLOCK_1.get(), context -> new FridgeFreezerBlock1TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.FRIDGE_FREEZER_BLOCK_2.get(), context -> new FridgeFreezerBlock2TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.OAK_WARDROBE_1.get(), context -> new OakWardrobe1TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.OAK_WARDROBE_2.get(), context -> new OakWardrobe2TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DARKOAKWARDROBE_1.get(), context -> new Darkoakwardrobe1TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.DARKOAKWARDROBE_2.get(), context -> new Darkoakwardrobe2TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.SPRUCE_WARDROBE_1.get(), context -> new SpruceWardrobe1TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.SPRUCE_WARDROBE_2.get(), context -> new SpruceWardrobe2TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.ACACIA_WARDROBE_1.get(), context -> new AcaciaWardrobe1TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.ACACIA_WARDROBE_2.get(), context -> new AcaciaWardrobe2TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.BIRCH_WARDROBE_1.get(), context -> new BirchWardrobe1TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.BIRCH_WARDROBE_2.get(), context -> new BirchWardrobe2TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.JUNGLE_WARDROBE_1.get(), context -> new JungleWardrobe1TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.JUNGLE_WARDROBE_2.get(), context -> new JungleWardrobe2TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.MANGROVE_WARDROBE_1.get(), context -> new MangroveWardrobe1TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.MANGROVE_WARDROBE_2.get(), context -> new MangroveWardrobe2TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.CRIMSON_WARDROBE_1.get(), context -> new CrimsonWardrobe1TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.CRIMSON_WARDROBE_2.get(), context -> new CrimsonWardrobe2TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.WARPED_WARDROBE_1.get(), context -> new WarpedWardrobe1TileRenderer());
		event.registerBlockEntityRenderer(LsFurnitureModBlockEntities.WARPED_WARDROBE_2.get(), context -> new WarpedWardrobe2TileRenderer());
	}
}
